config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  devise_for :users
  root to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check


  resources :experiences, only: [:new,:create, :update, :destroy]
  resources :searches, only: [:show, :new, :create, :update, :destroy] do
    collection do
      get :init, as: :init
    end
  end
  resources :favorites, only: [:create, :destroy]

  resources :workflows, only: [:show, :index]

  resources :binomes, only: [:new, :show, :create] do
    resources :messages, only: [:create]
  end

  get '/dashboard_searches', to: 'pages#dashboard_searches', as: :dashboard_searches
  get '/dashboard_favorites', to: 'pages#dashboard_favorites', as: :dashboard_favorites
  get '/dashboard_profile', to: 'pages#dashboard_profile', as: :dashboard_profile
  get '/dashboard_binomes', to: 'pages#dashboard_binomes', as: :dashboard_binomes
  get '/dashboard_binomes_unread', to: 'pages#dashboard_binomes_unread', as: :dashboard_binomes_unread
  post '/dashboard_searches/:search_id/details/:user_id', to: 'searches#details', as: :search_details
  get '/dashboard_workflows', to: 'pages#dashboard_workflows', as: :dashboard_workflows
  # Defines the root path route ("/")
end

app/models/binome.rb
class Binome < ApplicationRecord
  belongs_to :user_1, class_name: "User", foreign_key: :user_1_id
  belongs_to :user_2, class_name: "User", foreign_key: :user_2_id
  has_many :messages, dependent: :destroy
  has_one :workflow, dependent: :destroy
  has_many :coachings, dependent: :destroy

  validates :user_1_id, uniqueness: { scope: :user_2_id, message: "Binome already exists between these users" }

  def participants
    [user_1, user_2]
  end

  def other_user(current_user)
    current_user == user_1 ? user_2 : user_1
  end

  # def self.ordered_by_last_message
  #   left_joins(:messages)
  #     .group(:id)
  #     .order('MAX(messages.created_at) DESC NULLS LAST')
  # end
end

app/controllers/binomes_controller.rb
class BinomesController < ApplicationController
  before_action :set_binome, only: [:show]


  def index
    @binomes = current_user.binomes
  end

  def show
    @message = Message.new
    @users = User.where.not(id: current_user.id)
    @binomes = Binome.where("user_1_id = :user_id OR user_2_id = :user_id", user_id: current_user.id)
    @binome.messages.where(sender: @binome.other_user(current_user), reading: false).update_all(reading: true)
  end

  def new
    @binome = Binome.new
    @binome.find_by(user_1: current_user, user_2: @user)

  end

  def create
    if Binome.find_by(user_1: current_user, user_2_id: params[:binome][:recipient_id])
      redirect_to dashboard_binomes_path(@binome), notice: 'Binome was successfully found.'
    else
      @binome = Binome.new(binome_params)
      @binome.user_1 = current_user
      @binome.user_2 = User.find(params[:binome][:recipient_id])
      if @binome.save
        Message.create!(binome: @binome, sender: current_user, content: params[:binome][:message])
        redirect_to dashboard_searches_path, notice: 'Message successfully sent.'
      else
        redirect_to dashboard_searches_path, alert: "Impossible de créer la conversation"
      end
    end
  end

  private

  def set_binome
    @binome = Binome.find(params[:id])
    unless @binome.user_1 == current_user || @binome.user_2 == current_user
      redirect_to root_path, alert: "You don't have access to this chat"
    end
  end

  def binome_params
    params.require(:binome).permit(:name, :user_2_id)
  end
end

app/views/binomes/_new_binome_modal.html.erb
<div class="modal fade"
     id="newBinomeModal-<%= @user.id %>"
     tabindex="-1"
     aria-labelledby="newBinomeModal-<%= @user.id %>Label"
     aria-hidden="true">
     <div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
  <h5 class="modal-title" id="newBinomeModal-<%= @user.id %>Label">Message</h5>
  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>

<% @binome = Binome.find_by(user_1: current_user, user_2: @user) || Binome.new %>

<%= form_with(
      model: @binome,
      url: binomes_path,
      local: true,
      data: { controller: "binome", turbo: false },
      method: :post
    ) do |f| %>
  <div class="modal-body">
    <div class="mb-3">
      <%= f.text_field :message,
          class: "form-control",
          placeholder: "Votre message...",
          required: true
      %>
    </div>
    <%= f.hidden_field :recipient_id, value: @user.id if @user %>
    <%#= f.hidden_field :user_2_id, value: @user.id %>
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
    <%= f.submit "Envoyer", class: "btn btn-primary" %>
  </div>
<% end %>

  </div>
</div>

</div>

app/views/binomes/index.html.erb
<%# le link de l'icone nouveau binome
<%= link_to 'New Binome', new_binome_path %>

app/views/binomes/new.html.erb
<div class="modal fade"
     id="newBinomeModal"
     tabindex="-1"
     aria-labelledby="newBinomeModalLabel"
     aria-hidden="true">
     <div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
  <h5 class="modal-title" id="newBinomeModalLabel">Message</h5>
  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<%= form_with(
      model: @binome,
      url: binomes_path,
      local: true,
      data: { controller: "binome", turbo: false },
      method: :post
    ) do |f| %>
  <div class="modal-body">
    <div class="mb-3">
      <%= f.text_area :message,
          class: "form-control",
          placeholder: "écrivez votre message ici...",
          rows: 3,
          required: true
      %>
    </div>
    <%= f.hidden_field :recipient_id, value: @user.id if @user %>
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
    <%= f.submit "Envoyer", class: "btn btn-primary" %>
  </div>
<% end %>

  </div>
</div>

</div>

app/views/binomes/show.html.erb
<%= turbo_frame_tag "binome_content" do %>
  <div class="chat">
    <%= turbo_stream_from [@binome, current_user, "messages"] %>
    <div id="messages" class="messages">
      <% @binome.messages.each do |message| %>
        <%= render "messages/message", message: message, user: current_user %>
      <% end %>
    </div>

    <div class="message-form bg-white sticky-bottom">
      <%= simple_form_for [@binome, @message],
          html: {class: "d-flex w-100"},
          data: { turbo_stream: true,
                 controller: "reset-form",
                 action: "turbo:submit-end->reset-form#reset" } do |f| %>
        <%= f.input :content,
          label: false,
          placeholder: "Écrivez un message...",
          wrapper_html: {class: "flex-grow-1"},
          input_html: {class: "bg-transparent"}
        %>
        <%= f.button :submit, "Envoyer", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
<% end %>