config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  devise_for :users
  root to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check


  resources :experiences, only: [:new,:create, :update, :destroy]
  resources :searches, only: [:show, :new, :create, :update, :destroy] do
    collection do
      get :init, as: :init
    end
  end
  resources :favorites, only: [:create, :destroy]

  resources :workflows, only: [:show, :index]

  resources :binomes, only: [:new, :show, :create] do
    resources :messages, only: [:create]
  end

  get '/dashboard_searches', to: 'pages#dashboard_searches', as: :dashboard_searches
  get '/dashboard_favorites', to: 'pages#dashboard_favorites', as: :dashboard_favorites
  get '/dashboard_profile', to: 'pages#dashboard_profile', as: :dashboard_profile
  get '/dashboard_binomes', to: 'pages#dashboard_binomes', as: :dashboard_binomes
  get '/dashboard_binomes_unread', to: 'pages#dashboard_binomes_unread', as: :dashboard_binomes_unread
  post '/dashboard_searches/:search_id/details/:user_id', to: 'searches#details', as: :search_details
  get '/dashboard_workflows', to: 'pages#dashboard_workflows', as: :dashboard_workflows
  # Defines the root path route ("/")
end

app/views/pages/_tabs.html.erb
<div class="tabs-background">
  <div>
    <h1 class="tabs-titles">En route vers le temps partiel </h1>
    <%# <h2 class="tabs-sub-titles">Mon tableau de bord</h2> %>
  </div>

  <div class="tabs-with-pics">

    <%#= action_name %>
    <%#= controller_name %>
    <ul class="nav nav-tabs flex-item">
      <li class="nav-item">
        <%= link_to "Mes recherches", dashboard_searches_path, class: "nav-link #{'active' if action_name == 'dashboard_searches'}" %>
      </li>
      <li class="nav-item">
        <%= link_to "Mes profils favoris", dashboard_favorites_path, class: "nav-link #{'active' if action_name == 'dashboard_favorites'}" %>
      </li>
      <li class="nav-item">
        <%= link_to "Messages (#{@number})", dashboard_binomes_path, class: "nav-link #{'active' if action_name == 'dashboard_binomes'}" %>
      </li>
      <li class="nav-item">
        <%= link_to "Mon profil", dashboard_profile_path, class: "nav-link #{'active' if action_name == 'dashboard_profile'}" %>
      </li>
      <li class="nav-item">
        <%= link_to "Espace de travail", dashboard_workflows_path, class: "nav-link #{'active' if action_name == 'index' && controller_name == 'workflows'}" %>
      </li>
    </ul>

    <div class="tabs-buttons">
      <%= button_to init_searches_path, method: :get, class: "round-cta" do %>
        <i class="fa-solid fa-plus"></i>
      <% end %>
      <%= button_to dashboard_searches_path, method: :get, class: "round-cta" do %>
        <i class="fa-solid fa-gear"></i>
      <% end %>
    </div>

  </div>

</div>

app/views/pages/dashboard_binomes.html.erb
<div class="dashboard-container" data-controller="active-chat" >
  <div><%= render "tabs" %></div>
  <div class="container-fluid">
    <div class="card">
      <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs">
          <li class="nav-item">
            <a class="nav-link active" href="#"><i class="fas fa-inbox"></i> Inbox</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#"><i class="fas fa-search"></i> Search messages</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="dashboard_binomes_unread"><i class="fas fa-envelope"></i> Unread - <%= @number%></a>
          </li>
        </ul>
      </div>
      <div class="card-body">
        <div class="row">
          <!-- binomes List Column -->
          <div class="col-md-3 binomes-list">
            <h4>Les nouveaux messages</h4>
            <ul class="list-group">
              <% if @binomes.present? %>
                <div class="binome-preview">
                  <% @binomes.each do |binome| %>
                    <%= link_to binome_path(binome), data: { turbo_frame: "binome_content" } do %>
                      <div class="chatroom-info" data-action="click->active-chat#highlight" data-active-chat-target="info">
                        <div class="chatroom-info-without-chevron">
                          <div class="avatar">
                            <% if binome.other_user(current_user).photo.attached? %>
                              <%= cl_image_tag binome.other_user(current_user).photo.key, crop: :fill, class: "avatar" %>
                            <% else %>
                              <%= image_tag "default-user.svg", crop: :fill, alt: "default-profile-photo"%>
                            <% end %>
                          </div>
                          <div class="name-and-notif">
                            <h5><%= binome.other_user(current_user).first_name %> <%= binome.other_user(current_user).last_name %></h5>
                            <% if binome.messages.where(sender: binome.other_user(current_user), reading: false).count > 0 %>
                              <%= turbo_stream_from [binome, current_user] %>
                                <div class="badge rounded-pill text-bg-info">
                                  <% if binome.messages.where(sender: binome.other_user(current_user), reading: false).count == 1 %>
                                    <p>1 message non lu</p>
                                  <% else %>
                                    <p><%= binome.messages.where(sender: binome.other_user(current_user), reading: false).count %> messages non lus</p>
                                  <% end %>
                                </div>
                              <%# <p class="last-message"></p>
                              <%= binome.messages.last.content.truncate(7) %>
                              <%# <small> ago</small> %>
                            <% end %>
                          </div>
                        </div>
                        <h3><i class="fa-solid fa-chevron-right"></i></h3>
                      </div>
                    <% end %>
                  <% end %>
                </div>
              <% else %>
                <li class="list-group-item">No chatrooms available</li>
              <% end %>
            </ul>
          </div>
          <!-- Message Exchanges Column -->
          <div class="col-md-9">
            <%= turbo_frame_tag "binome_content" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/dashboard_binomes_unread.html.erb
<div class="dashboard-container">
  <div><%= render "tabs" %></div>
<div class="container-fluid">
  <div class="card">
    <div class="card-header">
      <ul class="nav nav-tabs card-header-tabs">
        <li class="nav-item">
          <a class="nav-link" href="dashboard_binomes"><i class="fas fa-inbox"></i> Inbox</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#"><i class="fas fa-search"></i> cherchez un message</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="#"><i class="fas fa-envelope"></i> Messages non lus - <%= @number%></a>
        </li>
      </ul>
    </div>
    <div class="card-body">
      <div class="row">
        <!-- binomes List Column -->
        <div class="col-md-3 binomes-list">
          <h4>Votre messagerie</h4>
          <ul class="list-group">
            <% if @binomes.present? %>
              <% @binomes.each do |binome| %>
              <% if binome.messages.where(sender: binome.other_user(current_user), reading: false).count > 0%>
                <%= link_to binome_path(binome), data: { turbo_frame: "binome_content" } do %>
                  <div class="chatroom-preview">
                    <div class="avatar">
                      <%= image_tag "", class: "img-thumbnail" %>
                    </div>
                    <div class="chatroom-info">
                      <h5><%= binome.other_user(current_user).first_name %> <%= binome.other_user(current_user).last_name %></h5>
                      <% if binome.messages.any? %>
                      <%= turbo_stream_from [binome, current_user] %>
                        <div class="badge rounded-pill text-bg-info">Unread : <%= binome.messages.where(sender: binome.other_user(current_user), reading: false).count %></div>
                        <p class="last-message">
                          <%= binome.messages.last.content.truncate(50) %>
                        </p>
                        <small><%= time_ago_in_words(binome.messages.last.created_at) %> ago</small>
                      <% end %>
                    </div>
                  </div>
                <% end %>
              <% end %>
              <% end %>
            <% else %>
              <li class="list-group-item">No binome available</li>
            <% end %>
          </ul>
        </div>

        <!-- Message Exchanges Column -->
        <div class="col-md-9">
          <%= turbo_frame_tag "binome_content" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/dashboard_chatrooms.html.erb
<div class="dashboard-container" data-controller="active-chat" >
  <div><%= render "tabs" %></div>
  <div class="container-fluid">
    <div class="card">
      <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs">
          <li class="nav-item">
            <a class="nav-link active" href="#"><i class="fas fa-inbox"></i> Inbox</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#"><i class="fas fa-search"></i> Search messages</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="dashboard_chatrooms_unread"><i class="fas fa-envelope"></i> Unread - <%= @number%></a>
          </li>
        </ul>
      </div>
      <div class="card-body">
        <div class="row">
          <!-- Chatrooms List Column -->
          <div class="col-md-3 chatrooms-list">
            <h4>Les nouveaux messages</h4>
            <ul class="list-group">
              <% if @chatrooms.present? %>
                <div class="chatroom-preview">
                  <% @chatrooms.each do |chatroom| %>
                    <%= link_to chatroom_path(chatroom), data: { turbo_frame: "chatroom_content" } do %>
                      <div class="chatroom-info" data-action="click->active-chat#highlight" data-active-chat-target="info">
                        <div class="chatroom-info-without-chevron">
                          <div class="avatar">
                            <% if chatroom.other_user(current_user).photo.attached? %>
                              <%= cl_image_tag chatroom.other_user(current_user).photo.key, crop: :fill, class: "avatar" %>
                            <% else %>
                              <%= image_tag "default-user.svg", crop: :fill, alt: "default-profile-photo"%>
                            <% end %>
                          </div>
                          <div class="name-and-notif">
                            <h5><%= chatroom.other_user(current_user).first_name %> <%= chatroom.other_user(current_user).last_name %></h5>
                            <% if chatroom.messages.where(sender: chatroom.other_user(current_user), reading: false).count > 0 %>
                              <%= turbo_stream_from [chatroom, current_user] %>
                                <div class="badge rounded-pill text-bg-info">
                                  <% if chatroom.messages.where(sender: chatroom.other_user(current_user), reading: false).count == 1 %>
                                    <p>1 message non lu</p>
                                  <% else %>
                                    <p><%= chatroom.messages.where(sender: chatroom.other_user(current_user), reading: false).count %> messages non lus</p>
                                  <% end %>
                                </div>
                              <%# <p class="last-message"></p>
                              <%= chatroom.messages.last.content.truncate(7) %>
                              <%# <small> ago</small> %>
                            <% end %>
                          </div>
                        </div>
                        <h3><i class="fa-solid fa-chevron-right"></i></h3>
                      </div>
                    <% end %>
                  <% end %>
                </div>
              <% else %>
                <li class="list-group-item">No chatrooms available</li>
              <% end %>
            </ul>
          </div>
          <!-- Message Exchanges Column -->
          <div class="col-md-9">
            <%= turbo_frame_tag "chatroom_content" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/dashboard_chatrooms_unread.html.erb
<div class="dashboard-container">
  <div><%= render "tabs" %></div>
<div class="container-fluid">
  <div class="card">
    <div class="card-header">
      <ul class="nav nav-tabs card-header-tabs">
        <li class="nav-item">
          <a class="nav-link" href="dashboard_chatrooms"><i class="fas fa-inbox"></i> Inbox</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#"><i class="fas fa-search"></i> cherchez un message</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="#"><i class="fas fa-envelope"></i> Messages non lus - <%= @number%></a>
        </li>
      </ul>
    </div>
    <div class="card-body">
      <div class="row">
        <!-- Chatrooms List Column -->
        <div class="col-md-3 chatrooms-list">
          <h4>Votre messagerie</h4>
          <ul class="list-group">
            <% if @chatrooms.present? %>
              <% @chatrooms.each do |chatroom| %>
              <% if chatroom.messages.where(sender: chatroom.other_user(current_user), reading: false).count > 0%>
                <%= link_to chatroom_path(chatroom), data: { turbo_frame: "chatroom_content" } do %>
                  <div class="chatroom-preview">
                    <div class="avatar">
                      <%= image_tag "", class: "img-thumbnail" %>
                    </div>
                    <div class="chatroom-info">
                      <h5><%= chatroom.other_user(current_user).first_name %> <%= chatroom.other_user(current_user).last_name %></h5>
                      <% if chatroom.messages.any? %>
                      <%= turbo_stream_from [chatroom, current_user] %>
                        <div class="badge rounded-pill text-bg-info">Unread : <%= chatroom.messages.where(sender: chatroom.other_user(current_user), reading: false).count %></div>
                        <p class="last-message">
                          <%= chatroom.messages.last.content.truncate(50) %>
                        </p>
                        <small><%= time_ago_in_words(chatroom.messages.last.created_at) %> ago</small>
                      <% end %>
                    </div>
                  </div>
                <% end %>
              <% end %>
              <% end %>
            <% else %>
              <li class="list-group-item">No chatroom available</li>
            <% end %>
          </ul>
        </div>

        <!-- Message Exchanges Column -->
        <div class="col-md-9">
          <%= turbo_frame_tag "chatroom_content" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/dashboard_favorites.html.erb
<div class="dashboard-container">
  <div><%= render "tabs" %></div>

  <% if @favorites.any? %>
    <div class="matching-profiles">
      <% @favorites.each do |favorite| %>
        <% @favorite_user = User.find(favorite.user_2_id) %>
          <div class="profile-card">
            <div class="content-profile">
              <div class="profile-subcard">
                <div class="profile-info">
                  <% if @favorite_user.photo.attached? %>
                    <%= cl_image_tag @favorite_user.photo.key, crop: :fill, class: "avatar" %>
                  <% else %>
                    <%= image_tag "default-user.svg", crop: :fill, alt: "default-profile-photo"%>
                  <% end %>
                  <div class="profile-icons-box">
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#newBinomeModal">
                      <i class="fa-regular fa-message"></i>
                    </button>
                    <% if current_user.favorites.exists?(user_2_id: @favorite_user.id) %>
                      <!-- Si l'utilisateur a déjà favorisé ce profil, on affiche l'étoile pleine -->
                      <%= button_to favorites_path(user_2_id: @favorite_user.id), method: :post, data: {turbo: false} do %>
                      <i class="fa-solid fa-star text-warning"></i>
                      <!-- L'étoile pleine si déjà favori -->
                      <% end %>
                    <% else %>
                      <!-- Si l'utilisateur n'a pas encore favorisé ce profil, on affiche l'étoile vide -->
                      <%= button_to favorites_path(user_2_id: @favorite_user.id), method: :post, data: {turbo: false} do%>
                      <i class="fa-regular fa-star"></i>
                      <!-- L'étoile vide si non favori -->
                      <% end %>
                    <% end %>
                  </div>
                </div>
                <div class="name-and-mail">
                  <h3 class="profile-name"><%= @favorite_user.first_name %> <%= @favorite_user.last_name %></h3>
                  <div class="mail-and-pic">
                    <div>
                      <i class="fas fa-envelope"></i>
                    </div>
                    <div>
                      <p class="profile-email">
                      <% if @favorite_user.email.length > 20 %>
                        <% regex_after_arobase = /@.*$/%>
                        <% if @favorite_user.email.match(regex_after_arobase)[0].length > 12%>
                          <% regex_twelve_letters = /.{15}/%>
                          <% twelve_letters = @favorite_user.email.match(regex_twelve_letters)[0] %>
                          <%= twelve_letters%>...
                        <% else%>
                          <%first_letter_email = /^./%>
                          <%= @favorite_user.email.match(first_letter_email)[0]%>...<%=@favorite_user.email.match(regex_after_arobase)[0] %>
                        <% end %>
                      <% else%>
                        <%= @favorite_user.email%>
                      <% end%>
                      </p>
                    </div>
                  </div>
                </div>
              </div>
              <div class="separator"></div>
              <div class="profile-experiences">
                <div>
                  <p><strong><%= @favorite_user.experiences.last.postname %> chez <%= @favorite_user.experiences.last.firm %></strong></p>
                  <p><em>" <%= @favorite_user.description %> "</em></p>
                </div>
              </div>
            </div>
          </div>





      <% end %>
    </div>
<% else %>
    <p class="no-results">Pas de profils sauvegardés pour le moment</p>
  <% end %>
</div>

app/views/pages/dashboard_profile.html.erb
<div class="dashboard-container">
  <div><%= render "tabs" %></div>

<div class="d-flex justify-content-evenly">

  <div class="flex-item container-profile-exp">
  <h2 class="text-center">Mes expériences</h2>
    <%if current_user.experiences.any?%>
      <% current_user.experiences.each do |experience| %>
        <div class="exp">
          <% if experience.is_current%>
            <h4>Poste actuel</h4>
            <p>Depuis <%= experience.start_date %></p>
          <% else %>
            <h4>Expérience passée</h4>
            <p>De <%= experience.start_date %> à <%= experience.end_date %></p>
          <% end %>
            <p><strong>Métier :</strong> <%= experience.line_of_work %></p>
            <p><strong>Secteur :</strong> <%= experience.field %></p>
        </div>
      <% end %>
    </div>

    <div class="flex-item">
      <section class="profile-content">
        <%= render "experiences/form", experience: @experience %>
      </section>
    </div>

  </div>

<% else %>
  <section class="profile-content">
    <%= render "experiences/form", experience: @experience %>
  </section>
<% end %>

app/views/pages/dashboard_searches.html.erb
<div class="dashboard-container">
  <div><%= render "tabs" %></div>

  <div class="searches-results">
    <div class="searches-container">
      <% @searches.each do |search| %>
        <%= link_to search_path(search), data: { turbo_frame: "preview" } do %>
          <% if search.is_offering? %>
            <div class="search-card">
              <div class="header-searches-invite">
                <h3>Partager mon poste</h3>
                <h3><i class="fa-solid fa-chevron-right"></i></h3>
              </div>
              <div class="search-card-content">
                <div class="content-item">
                  <div class="line-of-work"><%= search.line_of_work.capitalize %></div>
                  <div class="adress"><%= search.address %></div>
                  </div>
                <div class="div-time-share-invite">40%</div>
              </div>
            </div>
          <% else %>
            <div class="search-card">
              <div class="header-searches-join">
                <h3>Rejoindre un poste</h3>
                <h3><i class="fa-solid fa-chevron-right"></i></h3>
              </div>
              <div class="search-card-content">
                <div class="content-item">
                  <div class="line-of-work"><%= search.line_of_work.capitalize %></div>
                  <div class="adress"><%= search.address %></div>
                </div>
                <div class="div-time-share-join">40%</div>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <div class="results" id="results">
      <%= turbo_frame_tag "preview" %>
    </div>
  </div>
  <div class="details">
    <%= turbo_frame_tag "details" %>
  </div>

  <% if current_user.searches.nil?%>
    <div class="cards">
      <h1>Aucun recherche ici</h1>
    </div>
  <%else%>
    <%#= render "cards_jobsearch" %>
  <% end %>
</div>

app/views/pages/dashboard_workflows.html.erb
<div class="dashboard-container">
  <div><%= render "tabs" %></div>

  <% if @workflows.any? %>
    <div class="matching-profiles">
      <% @workflows.each do |workflow| %>
        <% @binome_user = workflow.binome.user %>
          <div class="profile-card">
            <div class="content-profile">
              <div class="profile-subcard">
                <div class="profile-info">
                  <% if work.photo.attached? %>
                    <%= cl_image_tag @favorite_user.photo.key, crop: :fill, class: "avatar" %>
                  <% else %>
                    <%= image_tag "default-user.svg", crop: :fill, alt: "default-profile-photo"%>
                  <% end %>
                  <div class="profile-icons-box">
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#newBinomeModal">
                      <i class="fa-regular fa-message"></i>
                    </button>
                    <% if current_user.favorites.exists?(user_2_id: @favorite_user.id) %>
                      <!-- Si l'utilisateur a déjà favorisé ce profil, on affiche l'étoile pleine -->
                      <%= button_to favorites_path(user_2_id: @favorite_user.id), method: :post, data: {turbo: false} do %>
                      <i class="fa-solid fa-star text-warning"></i>
                      <!-- L'étoile pleine si déjà favori -->
                      <% end %>
                    <% else %>
                      <!-- Si l'utilisateur n'a pas encore favorisé ce profil, on affiche l'étoile vide -->
                      <%= button_to favorites_path(user_2_id: @favorite_user.id), method: :post, data: {turbo: false} do%>
                      <i class="fa-regular fa-star"></i>
                      <!-- L'étoile vide si non favori -->
                      <% end %>
                    <% end %>
                  </div>
                </div>
                <div class="name-and-mail">
                  <h3 class="profile-name"><%= @favorite_user.first_name %> <%= @favorite_user.last_name %></h3>
                  <div class="mail-and-pic">
                    <div>
                      <i class="fas fa-envelope"></i>
                    </div>
                    <div>
                      <p class="profile-email">
                      <% if @favorite_user.email.length > 20 %>
                        <% regex_after_arobase = /@.*$/%>
                        <% if @favorite_user.email.match(regex_after_arobase)[0].length > 12%>
                          <% regex_twelve_letters = /.{15}/%>
                          <% twelve_letters = @favorite_user.email.match(regex_twelve_letters)[0] %>
                          <%= twelve_letters%>...
                        <% else%>
                          <%first_letter_email = /^./%>
                          <%= @favorite_user.email.match(first_letter_email)[0]%>...<%=@favorite_user.email.match(regex_after_arobase)[0] %>
                        <% end %>
                      <% else%>
                        <%= @favorite_user.email%>
                      <% end%>
                      </p>
                    </div>
                  </div>
                </div>
              </div>
              <div class="separator"></div>
              <div class="profile-experiences">
                <div>
                  <p><strong><%= @favorite_user.experiences.last.postname %> chez <%= @favorite_user.experiences.last.firm %></strong></p>
                  <p><em>" <%= @favorite_user.description %> "</em></p>
                </div>
              </div>
            </div>
          </div>





      <% end %>
    </div>
<% else %>
    <p class="no-results">Pas de profils sauvegardés pour le moment</p>
  <% end %>
</div>

app/views/pages/form_contact.html.erb
<form action="", method="POST">
  <label for="objet"></label>
  <input type="text" name="objet_value" id="objet">
  <label for="message"></label>
  <input type="text" name="message_value" id="message">
</form>

app/views/pages/home.html.erb
<%# <h1>Pages#home</h1> %>
<%# <p>Find me in app/views/pages/home.html.erb</p> %>
<div class="home-background-1 home-container">

  <%# div with title, picture and CTA %>

  <div class="home-with-pic">
    <div class="home-header-and-CTA">
        <h1><span>Passez à temps partiel. <br/></span> Grâce au jobsharing</h1>
        <% if user_signed_in? %>
          <%= link_to "Je cherche un binôme", init_searches_path,
                      class: "main-cta-home" %>
        <% else %>
          <%= link_to "Je cherche un binôme", new_user_registration_path,
                      class: "main-cta-home" %>
        <% end %>
    </div>

    <%# div with home picture %>

    <div>
      <%= image_tag "Allura - Feedback Session.png", alt: "two-women-jobsharing", height: 350 %>
    </div>
  </div>
  <%# display-flex with 3 marketing promesses %>
  <div id="promess">
    <div class="mini-card-home">
      <h2>Flexibilité</h2>
      <p>Choisissez <br/>votre temps de travail</p>
    </div>
    <div class="mini-card-home">
      <h2>Equilibre</h2>
      <p>Gardez du temps <br/>pour vos projets personnels</p>
    </div>
    <div class="mini-card-home">
      <h2>Performance</h2>
      <p>Epanouissez-vous <br/>sans compromis dans votre carrière</p>
    </div>
  </div>

  <%# div with call to action scroll down %>
  <div class="scroll-down">
    <i class="fa-solid fa-chevron-down"></i>
  </div>
</div>

<%# page d'information %>

<div class="home-background-2 home-left-spacing" id="home-section-2">
<div class="col steps-to-jobsharing">
<div class="row cards-steps-to-jobsharing">

</div>
</div>
</div>