config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  devise_for :users
  root to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check


  resources :experiences, only: [:new,:create, :update, :destroy]
  resources :searches, only: [:show, :new, :create, :update, :destroy] do
    collection do
      get :init, as: :init
    end
  end
  resources :favorites, only: [:create, :destroy]

  resources :workflows, only: [:show, :index]

  resources :binomes, only: [:new, :show, :create] do
    resources :messages, only: [:create]
  end

  get '/dashboard_searches', to: 'pages#dashboard_searches', as: :dashboard_searches
  get '/dashboard_favorites', to: 'pages#dashboard_favorites', as: :dashboard_favorites
  get '/dashboard_profile', to: 'pages#dashboard_profile', as: :dashboard_profile
  get '/dashboard_binomes', to: 'pages#dashboard_binomes', as: :dashboard_binomes
  get '/dashboard_binomes_unread', to: 'pages#dashboard_binomes_unread', as: :dashboard_binomes_unread
  post '/dashboard_searches/:search_id/details/:user_id', to: 'searches#details', as: :search_details
  get '/dashboard_workflows', to: 'pages#dashboard_workflows', as: :dashboard_workflows
  # Defines the root path route ("/")
end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :user
  has_many :searches, dependent: :destroy

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController

  def create
    @experience = Experience.new(experience_params)
    @experience.user = current_user
    @experience.save!
    redirect_to dashboard_profile_path
  end
  
  def update
    @experience = Experience.find(params[:id])
    @experience.update(experience_params)
    redirect_to # à définir
  end

  def destroy
    @experience.find(params[:id])
    @experience.destroy
    # path à définir
    redirect_to somewhere_path, status: :see_other
  end

  private

  def experience_params
    params.require(:experience).permit(:user_id, :start_date, :end_date, :is_current, :line_of_work, :field, :address)
  end

end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/views/experiences/_form.html.erb
<div class="container-profile-exp">
  
  <h2 class="text-center">Ajouter une expérience</h1>

  <%= simple_form_for @experience do |f| %>

    <%= f.input :start_date,
                as: :string,
                label: "Date de début",
                input_html: { data: { controller: "datepicker" } } %>

    <%= f.input :end_date,
                as: :string,
                label: "Date de fin",
                input_html: { data: { controller: "datepicker" } } %>

    <%= f.input :is_current, label: 'Est-ce votre poste actuel ?', input_html: { class: 'form-check-input' } %>

    <%= f.input :line_of_work, label: 'Ligne de métier', input_html: { class: 'form-control' }, collection: @lines_of_work, prompt: 'Sélectionnez une ligne de métier', required: true %>

    <%= f.input :field, label: "Secteur d'activité", input_html: { class: 'form-control' }, collection: @fields, prompt: "Sélectionnez un secteur d'activité", required: true %>

    <%= f.input :address,
                  label: "Adresse",
                  input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
                  wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_ACCESS_TOKEN"]}}%>

    <div class="text-center mt-3">
      <%= f.button :submit, 'Créer l\'expérience', class: 'btn btn-primary' %>
      <%= link_to 'Retour', experiences_path, class: 'btn btn-secondary' %>
    </div>
  <% end %>
</div>