config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  devise_for :users
  root to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check


  resources :experiences, only: [:new,:create, :update, :destroy]
  resources :searches, only: [:show, :new, :create, :update, :destroy] do
    collection do
      get :init, as: :init
    end
  end
  resources :favorites, only: [:create, :destroy]

  resources :workflows, only: [:show, :index]

  resources :binomes, only: [:new, :show, :create] do
    resources :messages, only: [:create]
  end

  get '/dashboard_searches', to: 'pages#dashboard_searches', as: :dashboard_searches
  get '/dashboard_favorites', to: 'pages#dashboard_favorites', as: :dashboard_favorites
  get '/dashboard_profile', to: 'pages#dashboard_profile', as: :dashboard_profile
  get '/dashboard_binomes', to: 'pages#dashboard_binomes', as: :dashboard_binomes
  get '/dashboard_binomes_unread', to: 'pages#dashboard_binomes_unread', as: :dashboard_binomes_unread
  post '/dashboard_searches/:search_id/details/:user_id', to: 'searches#details', as: :search_details
  get '/dashboard_workflows', to: 'pages#dashboard_workflows', as: :dashboard_workflows
  # Defines the root path route ("/")
end

app/models/search.rb
class Search < ApplicationRecord
  belongs_to :user
  belongs_to :experience, optional: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def coordinates(format: :geocoder)
    if format == :geocoder
      [latitude, longitude]
    elsif format == :mapbox
      [longitude, latitude]
    end
  end

  LINES_OF_WORK = [
    "Ventes",
    "Production",
    "Achats",
    "Maintenance",
    "Logistique",
    "Marketing",
    "Comptabilité",
    "Contrôle de gestion",
    "Trésorerie"
  ]

  FIELDS = [
    "Agroalimentaire",
    "Banque & Assurance",
    "Bois, Papier & Carton",
    "Imprimerie",
    "BTP",
    "Matériaux de construction",
    "Chimie & Parachimie",
    "Commerce, Négoce & Distribution",
    "Édition, Communication & Multimédia",
    "Électronique & Électricité",
    "Études et conseils",
    "Industrie pharmaceutique",
    "Informatique & Télécoms",
    "Machines et équipements & Automobile",
    "Métallurgie & Travail du métal",
    "Plastique & Caoutchouc",
    "Services-aux-entreprises",
    "Textile, Habillement & Chaussure",
    "Transports & Logistique"
  ]

  DEPARTMENTS = [
    "1 Ain",
    "2 Aisne",
    "3 Allier",
    "4 Alpes-de-Haute-Provence",
    "5 Hautes-Alpes",
    "6 Alpes-Maritimes",
    "7 Ardèche",
    "8 Ardennes",
    "9 Ariège",
    "10	Aube",
    "11	Aude",
    "12	Aveyron",
    "13	Bouches-du-Rhône",
    "14	Calvados",
    "15	Cantal",
    "16	Charente",
    "17	Charente-Maritime",
    "18	Cher",
    "19	Corrèze",
    "2A	Corse-du-Sud",
    "2B	Haute-Corse",
    "21	Côte-d'Or",
    "22	Côtes d'Armor",
    "23	Creuse",
    "24	Dordogne",
    "25	Doubs",
    "26	Drôme",
    "27	Eure",
    "28	Eure-et-Loir",
    "29	Finistère",
    "30	Gard",
    "31	Haute-Garonne",
    "32	Gers",
    "33	Gironde",
    "34	Hérault",
    "35	Ille-et-Vilaine",
    "36	Indre",
    "37	Indre-et-Loire",
    "38	Isère",
    "39	Jura",
    "40	Landes",
    "41	Loir-et-Cher",
    "42	Loire",
    "43	Haute-Loire",
    "44	Loire-Atlantique",
    "45	Loiret",
    "46	Lot",
    "47	Lot-et-Garonne",
    "48	Lozère",
    "49	Maine-et-Loire",
    "50	Manche",
    "51	Marne",
    "52	Haute-Marne",
    "53	Mayenne",
    "54	Meurthe-et-Moselle",
    "55	Meuse",
    "56	Morbihan",
    "57	Moselle",
    "58	Nièvre",
    "59	Nord",
    "60	Oise",
    "61	Orne",
    "62	Pas-de-Calais",
    "63	Puy-de-Dôme",
    "64	Pyrénées-Atlantiques",
    "65	Hautes-Pyrénées",
    "66	Pyrénées-Orientales",
    "67	Bas-Rhin",
    "68	Haut-Rhin",
    "69	Rhône",
    "70	Haute-Saône",
    "71	Saône-et-Loire",
    "72	Sarthe",
    "73	Savoie",
    "75	Paris",
    "76	Seine-Maritime",
    "77	Seine-et-Marne",
    "78	Yvelines",
    "79	Deux-Sèvres",
    "80	Somme",
    "81	Tarn",
    "82	Tarn-et-Garonne",
    "83	Var",
    "84	Vaucluse",
    "85	Vendée",
    "86	Vienne",
    "87	Haute-Vienne",
    "88	Vosges",
    "89	Yonne",
    "90	Territoire-de-Belfort",
    "91	Essonne",
    "92	Hauts-de-Seine",
    "93	Seine-Saint-Denis",
    "94	Val-de-Marne",
    "95	Val-D'Oise",
    "971	Guadeloupe",
    "972	Martinique",
    "973	Guyane",
    "974	La Réunion",
    "976	Mayotte",
    "975	Saint-Pierre-et-Miquelon",
    "977	Saint-Barthélémy",
    "978	Saint-Martin",
    "987	Polynésie française",
    "989	Île de Clipperton",
    "986	Wallis-et-Futuna",
    "988	Nouvelle-Calédonie",
    "984	Terres australes et antarctiques françaises"
  ]
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def show
    @search = Search.find(params[:id])
    # Installer geocoder
    # Configurer geocoder pour fonctionner avec Mapbox
    # Regarder le cours sur geocoder pour mettre la bonne méthode (geocoded_by) dans le model qui contient l'adresse (experience)
    # Essayer de joindre les utilisateurs et les experiences (.joins)

    @matching_experiences = Experience.near(@search.address, 10).map(&:id)
    @matching_users = User.joins(:experiences)
                       .where(experiences: {
                         id: @matching_experiences,
                         line_of_work: @search.line_of_work,
                         field: @search.field,
                         is_current: true
                       })
                       .where.not(id: current_user.id)
                       .distinct

    # Essayer de faire un .where sur les experiences qui ont la même adresse que la search (utiliser .near)
    # et .where sur les experiences qui ont le même line_of_work que la search
    # et .where sur les experiences qui ont le même field que la search

  end

  def details
    @search = Search.find(params[:search_id])
    @user = User.find(params[:user_id])

    respond_to &:turbo_stream
  end

  def new
    # @experience = current_user.experiences.where(is_current: true)
    # if @experience
    #   return
    # else
    if params[:search][:is_offering] == "false"
      @search = Search.new(is_offering: false)
    else
      @search = Search.new(is_offering: true, line_of_work: current_user.current_experience.line_of_work, field: current_user.current_experience.field, address: current_user.current_experience.address, experience: current_user.current_experience, user: current_user)
    end

    @lines_of_work = Search::LINES_OF_WORK
    @departments = Search::DEPARTMENTS
    @fields = Search::FIELDS
    # end
  end

  def init
    @search = Search.new
  end

  def create
    @search = Search.new(search_params)
    @search.user = current_user
  # else
    if @search.save
      redirect_to dashboard_searches_path
    else
      render 'new', status: :unprocessable_entity
    end
  # end
  end

  def update
    @search = Search.find(params[:id])
    @search.update(search_params)
    redirect_to # à définir
  end

  def destroy
    @search.find(params[:id])
    @search.destroy
    # path à définir
    redirect_to somewhere_path, status: :see_other
  end

  private

  def search_params
    params.require(:search).permit(:user_id, :experience_id, :line_of_work, :field, :address, :is_offering, :quotite_de_travail)
  end

end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_details_card.html.erb
<%= turbo_frame_tag 'preview' do %>
  <div class="profile-details-card">

    <div class="profile-details-header">
      <div class="big-photo-and-name">
        <!-- photo of the contact -->
        <% if user.photo.attached? %>
          <div class="card-detail-profile">
            <%= cl_image_tag user.photo.key, crop: :fill, class: "big-avatar" %>
          </div>
        <% end %>
        <!-- name of the contact -->
        <div><h2><%= user.first_name %> <%= user.last_name %></h2></div>
        <div class="mail-and-pic">
          <div>
            <i class="fas fa-envelope"></i>
          </div>
          <p class="profile-detail-email">
          <% if user.email.length > 20 %>
            <% regex_after_arobase = /.*$/%>
            <% if user.email.match(regex_after_arobase)[0].length > 12%>
              <% regex_twelve_letters = /.{15}/%>
              <% twelve_letters = user.email.match(regex_twelve_letters)[0] %>
              <%= twelve_letters%>...
            <% else%>
              <%first_letter_email = /^./%>
              <%= user.email.match(first_letter_email)[0]%>...<%=user.email.match(regex_after_arobase)[0] %>
            <% end %>
          <% else%>
            <%= user.email%>
          <% end%>
          </p>
          </div>
        </div><div>

      </div>
        <!-- boutons actionsvers favoris, message et fermer -->
      <div class="profile-icons-box">
        <button type="button"
            data-bs-toggle="modal"
            data-bs-target="#newBinomeModal-<%= user.id %>">
          <i class="fa-regular fa-message"></i>
        </button>
        <% if current_user.favorites.exists?(user_2_id: user.id) %>
          <!-- Si l'utilisateur a déjà favorisé ce profil, on affiche l'étoile pleine -->
          <%= button_to favorites_path(user_2_id: user.id), method: :post, data: {turbo: false} do %>
          <i class="fa-solid fa-star text-warning"></i>
          <!-- L'étoile pleine si déjà favori -->
          <% end %>
        <% else %>
          <!-- Si l'utilisateur n'a pas encore favorisé ce profil, on affiche l'étoile vide -->
          <%= button_to favorites_path(user_2_id: user.id), method: :post, data: {turbo: false} do%>
          <i class="fa-regular fa-star"></i>
          <!-- L'étoile vide si non favori -->
          <% end %>
        <% end %>
        <%= button_to search_path(search), method: :get, data: { turbo_frame: "preview" } do %>
          <i class="fa-solid fa-x"></i>
        <% end %>

      </div>
      </div>

    <div class="profile-details-body">
      </div>
      <div class="description-card">
        <p><%= user.description %></p>
      </div>
      <div class="separator"></div>
        <div class="profile-details-experiences">
          <% user.experiences.where(line_of_work: search.line_of_work, field: search.field).each do |experience| %>
            <div class="profile-details-experiences-cards">
              <div class="profile-details-experience-item">
                <i class="fa-regular fa-calendar"></i>
                <p><strong> du </strong> <%= experience.start_date %></p>
                <p><strong> au </strong> <%= experience.start_date %></p>
              </div>
              <div class="profile-details-experience-item">
                <i class="fas fa-briefcase"></i>
                <p><strong>Entreprise</strong> <%= experience.firm %></p>
              </div>
              <div class="profile-details-experience-item">
                <i class="fas fa-industry"></i>
                <p><strong>Poste: </strong><%= experience.postname %></p>
              </div>
              <div class="profile-details-experience-item">
                <i class="fas fa-map-marker-alt"></i>
                <p><strong>Lieu:</strong> <%= experience.address %></p>
              </div>
            </div>
          <% end %>
        </div>
    </div>
  </div>
<% end %>

app/views/searches/details.html.erb
<%= turbo_frame_tag "details" do %>
  <div class="profile-detail-card">

    <div class="profile-details-header">
      <div class="big-photo-and-name">
        <!-- photo of the contact -->
        <% if @user.photo.attached? %>
          <div class="card-detail-profile">
            <%= cl_image_tag @user.photo.key, crop: :fill, class: "img-fluid avatar" %>
          </div>
        <% end %>
        <!-- name of the contact -->
        <div><h2><%= @user.first_name %> <%= @user.last_name %></h2></div>
      </div>
        <!-- boutons actionsvers favoris, message et fermer -->
      <div class="boutons-icons">
        <button type="button"
            data-bs-toggle="modal"
            data-bs-target="#newBinomeModal-<%= @user.id %>">
          <i class="fa-regular fa-message"></i>
        </button>
        <% if current_user.favorites.exists?(user_2_id: @user.id) %>
          <!-- Si l'utilisateur a déjà favorisé ce profil, on affiche l'étoile pleine -->
          <%= button_to favorites_path(user_2_id: @user.id), method: :post, data: {turbo: false} do %>
          <i class="fa-solid fa-star text-warning"></i>
          <!-- L'étoile pleine si déjà favori -->
          <% end %>
        <% else %>
          <!-- Si l'utilisateur n'a pas encore favorisé ce profil, on affiche l'étoile vide -->
          <%= button_to favorites_path(user_2_id: @user.id), method: :post, data: {turbo: false} do%>
          <i class="fa-regular fa-star"></i>
          <!-- L'étoile vide si non favori -->
          <% end %>
        <% end %>
        <%= link_to search_path(@search), data: { turbo_frame: "preview" } do %>
          <i class="fa-solid fa-x"></i>
        <% end %>
      </div>
    </div>

    <div class="profile-details-body">
      <div class="name-and-mail">
        <h3 class="profile-name"><%= @user.first_name %> <%= @user.last_name %></h3>
        <div class="mail-and-pic">
          <div>
            <i class="fas fa-envelope"></i>
          </div>
          <div>
            <p class="profile-email">
            <% if @user.email.length > 20 %>
              <% regex_after_arobase = /@.*$/%>
              <% if @user.email.match(regex_after_arobase)[0].length > 12%>
                <% regex_twelve_letters = /.{15}/%>
                <% twelve_letters = @user.email.match(regex_twelve_letters)[0] %>
                <%= twelve_letters%>...
              <% else%>
                <%first_letter_email = /^./%>
                <%= @user.email.match(first_letter_email)[0]%>...<%=@user.email.match(regex_after_arobase)[0] %>
              <% end %>
            <% else%>
              <%= @user.email%>
            <% end%>
            </p>
          </div>
        </div>
      </div>
      <div class="separator"></div>
        <div class="profile-details-experiences">
          <% @user.experiences.where(line_of_work: @search.line_of_work, field: @search.field).each do |experience| %>
            <div class="profile-details-experiences-cards">
              <div class="profile-details-experience-item">
                <i class="fas fa-briefcase"></i>
                <p><strong>Entreprise</strong> <%= experience.firm %></p>
              </div>
              <div class="profile-details-experience-item">
                <i class="fas fa-industry"></i>
                <p><strong>Poste: </strong><%= experience.postname %></p>
              </div>
              <div class="profile-details-experience-item">
                <i class="fas fa-map-marker-alt"></i>
                <p><strong>Lieu:</strong> <%= experience.address %></p>
              </div>
            </div>
          <% end %>
        </div>
    </div>
  </div>
<% end %>

app/views/searches/details.turbo_stream.erb
<%= turbo_stream.update('results') do %>
  <%= render partial: 'details_card', locals: { user: @user, search: @search } %>
<% end %>

app/views/searches/init.html.erb
<div class="d-flex justify-content-center align-items-center" style="min-height: 80vh;">

  <div class="container-questions flex-item">

    <%= simple_form_for @search, url: new_search_path, method: :get do |f| %>

      <div data-controller="search-auto-fill", data-action="input->search-auto-fill#display">
          <%= f.input :is_offering, wrapper_html: { class: 'init-option' },
                      as: :select,
                      collection: [["Je partage mon poste.",true], ["Je cherche une personne ayant déjà un poste.",false]],
                      required: true,
                      as: :radio_buttons,
                      label: "Quelle est votre situation ?"%>
      </div>

      <div class="text-center">
        <%= f.submit'Lancer ma recherche', class: "btn btn-primary text-center" %>
      </div>
    <% end %>

  </div>

  <div class="flex-item">
    <%= image_tag "image-init.png", alt: "Bicephale", width: 500 %>
  </div>

</div>

app/views/searches/new.html.erb
<div class="d-flex justify-content-evenly align-items-center">


  <div class="container-questions flex-item">
    <%= simple_form_for @search do |f| %>
      <div class="column">
            <%= f.input :line_of_work, label: "Quelle est votre ligne de métier ?", input_html: { class: 'form-control' }, collection: @lines_of_work, required: true %>
            <%= f.input :field, label: "Quel est votre secteur d'activité ?", input_html: { class: 'form-control' }, collection: @fields, required: true %>
            <%= f.input :address,
                          label: "Où souhaitez-vous chercher ?",
                          input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
                          wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_ACCESS_TOKEN"]}}%>
                          
          <%= f.input :quotite_de_travail, label: "Combien de temps souhaitez-vous travailler ? (en %)", input_html: { class: 'form-control', type: 'number', min: 0, max: 100, step: 10 } %>

        <div class="text-center mt-4">
          <%= f.submit 'Lancer ma recherche', id: 'bright', class: 'btn btn-primary btn-lg px-4' %>
        </div>

        <%= f.input :is_offering, as: :hidden %>
        <%= f.input :experience_id, as: :hidden %>

      </div>
    <% end %>
  </div>

  <div class="flex-item">
    <%= image_tag "image-search.png", alt: "Recherche", width: 200 %>
  </div>

</div>

app/views/searches/show.html.erb
<%= turbo_frame_tag "preview" do %>
  <% if @matching_users.any? %>
    <div class="matching-profiles-with-title">
      <div><h2>Ces profils peuvent vous intéresser</h2></div>
      <div class="matching-profiles">
        <% @matching_users.each do |matching_user| %>
          <% @user = matching_user %>
          <%= render "binomes/new_binome_modal", user: @user %>
          <div class="profile-card">
            <div class="content-profile">
              <div class="profile-subcard">
                <div class="profile-info">
                  <% if @user.photo.attached? %>
                    <%= cl_image_tag @user.photo.key, crop: :fill, class: "img-fluid avatar" %>
                  <% else %>
                    <%= image_tag "default-user.svg", crop: :fill, alt: "default-profile-photo"%>
                  <% end %>
                  <div class="profile-icons-box">
                    <%= link_to search_details_path(@search, @user), data: { turbo_method: :post } do %>
                      <i class="fa-solid fa-ellipsis"></i>
                    <% end %>
                    <button type="button"
                    data-bs-toggle="modal"
                    data-bs-target="#newBinomeModal-<%= @user.id %>">
                      <i class="fa-regular fa-message"></i>
                    </button>
                    <% if current_user.favorites.exists?(user_2_id: @user.id) %>
                      <!-- Si l'utilisateur a déjà favorisé ce profil, on affiche l'étoile pleine -->
                      <%= button_to favorites_path(user_2_id: @user.id), method: :post, data: {turbo: false} do %>
                      <i class="fa-solid fa-star text-warning"></i>
                      <!-- L'étoile pleine si déjà favori -->
                      <% end %>
                    <% else %>
                      <!-- Si l'utilisateur n'a pas encore favorisé ce profil, on affiche l'étoile vide -->
                      <%= button_to favorites_path(user_2_id: @user.id), method: :post, data: {turbo: false} do%>
                      <i class="fa-regular fa-star"></i>
                      <!-- L'étoile vide si non favori -->
                      <% end %>
                    <% end %>
                  </div>
                </div>
                <div class="name-and-mail">
                  <h3 class="profile-name"><%= @user.first_name %> <%= @user.last_name %></h3>
                  <div class="mail-and-pic">
                    <div>
                      <i class="fas fa-envelope"></i>
                    </div>
                    <div>
                      <p class="profile-email">
                      <% if @user.email.length > 20 %>
                        <% regex_after_arobase = /@.*$/%>
                        <% if @user.email.match(regex_after_arobase)[0].length > 12%>
                          <% regex_twelve_letters = /.{15}/%>
                          <% twelve_letters = @user.email.match(regex_twelve_letters)[0] %>
                          <%= twelve_letters%>...
                        <% else%>
                          <%first_letter_email = /^./%>
                          <%= @user.email.match(first_letter_email)[0]%>...<%=@user.email.match(regex_after_arobase)[0] %>
                        <% end %>
                      <% else%>
                        <%= @user.email%>
                      <% end%>
                      </p>
                    </div>
                  </div>
                </div>
              </div>
              <div class="separator"></div>
              <div class="profile-experiences">


                  <div class="experience-section">
                    <div class="experience-item">
                      <p><%= @user.description %></p>
                    </div>
                  </div>

              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% else %>
    <p class="no-results">Aucun profil correspondant trouvé</p>
  <% end %>

<% end %>